services:
  portfolio:
    build: .
    container_name: portfolio
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload
    ports:
      - "8014:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

