services:
  buildkit:
    image: buildkit:latest
    container_name: buildkit
    build: .
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload
    ports:
      - "1997:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

