services:
  buildkit:
    image: buildkit:latest
    container_name: buildkit
    build: .
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 1997
      --reload
    ports:
      - "1997:1997"
    restart: always

